### ISSUE TITLE
Fix Broken on Resident Evil 2. 

### ISSUE THREAD

**Issue by gardotd426** [z0z0z/mf-installcab#12]
I have no idea if this has anything to do with Resident Evil 2 removing Denuvo, like idk if they changed anything else, but it seems now that this is broken for RE2. I got about 10 hours in-game with everything working perfectly, then I quit playing for a couple weeks and came back after they updated the game and removed Denuvo. Now, it crashes instantly, this is reproducible by going to the sewer where you put the VHS cassette in the VHS player and it plays the video. It crashes every time, at the same spot (where they call him a freak). And in the steam logs, you get this: `10440.892:0031:006c:trace:seh:call_teb_handler handler at 0x7bce09a0 returned 1
10440.892:0031:006c:warn:seh:call_stack_handlers exception data not found in L"MFPlat.DLL"
Unhandled exception: page fault on read access to 0x738a814d1c8 in 64-bit code (0x000007ff6ba51649).`

**Comment by gardotd426** [comment]
I acquired an mfplat.dll from another source and it actually started working. So it does seem to be the mfplat.dll file included in the repo. Like I said, I reproduced this about 8 times in the exact same spot with the exact same error message in the Steam log, and then switched the dll with another one and it worked instantly.

**Comment by z0z0z** [comment]
Can you tell me any possible info you think might help?

- What is the MD5 hash of the other mfplat.dll and/or it's source
- What distro
- What GPU and driver

I just played through Resident Evil 2 for the first time (actually all 4 routes + extras) these past few weeks after they removed Denuvo.

I did have a couple crashes, none reproducible though.

I watched the VHS tape in the sewers next to the chess piece puzzle.

**Comment by gardotd426** [comment]
```
md5sum ~/Downloads/mfplat/mfplat.dll
1b41e17f1f28b2762c2683f07f1caac7  /home/matt/Downloads/mfplat/mfplat.dll
```
I don't know what's going on. Like I said, the second I switched the mfplats, I immediately got through the sewer VHS scene, when it was crashing every single time with that same mfplat error, but now I just got to the west area lab where you play the next VHS tape and it's crashing again. I've tried the mfplat that fixed the sewer scene as well as the one from this repo. Can't figure out what the hell is going on.

Distro: Arch Linux
Drivers: mesa-aco-git 20.0.0_devel (newest version) I've tried it with ACO as well as with `RADV_PERFTEST=llvm`
GPU: XFX GTS XXX RX 580

**Comment by gardotd426** [comment]
Here's what I just did: 
1. Switched to the newest custom proton from Tk-Glitch with the "mf workaround" fix set to true in the configuration options before building. 
2. Reran `WINEPREFIX=~/Steam/steamapps/compatdata/883710/pfx sh /home/matt/gits/mf-installcab/install-mf-64.sh`
3. Re-copied the mfplat.dll into the application directory, overwriting the one that was in there already. Relaunched the game, and it finished the VHS scene without crashing. Before doing those steps, it had crashed about 6 times in a row without finishing the scene. 

I'm not sure what the deal is. It's like it fixes it temporarily, but the next time I get to a scene like that, it'll crash and I'll have to do it again. But I'll see how well this goes now with this custom proton build and post any crashes. If there's anything else for me to test or you need any information, let me know

**Comment by z0z0z** [comment]
It may have been helpful to completely delete the Wine prefix. As in:

- Delete `steamapps/compatdata/883710`
- Relaunch RE2 (with normal Proton or no other solutions that could conflict) to create a new prefix
- Close game, run script
- Play

**Comment by boistordu** [comment]
So is there different mfplat.dll or not ? 
I think I'm missing something and that it makes sense to you all and it's obvious but not to me. 
So does your script does everything from this tutorial point in defferent post of protondb?  
`https://steamcommunity.com/sharedfiles/filedetails/?id=1654060648`
So should I 
- just clone your git 
- delete the folder in compatdata
- run the game a first time to get the creation of the needed folder in compatdata
- run your command 
- copy mfplat.dll from your git to the common/game_folder/
- and then try to run the game

**Comment by boistordu** [comment]
So here some data:
it's  under fedora 31
1080 TI
wine according to the terminaal during your script runtime is 5.2
I've tried with proton 4.11-12 and proton5 
under direct 11 and direct 12
all the same result.
same result as in resident 7 actually, the media file that is supposed to be read begin with some white screen parasite like old tv without antenna. So basically I would say it's a problem with the mfplat.dll. 
Maybe because of the version of my graphic card that require another function in mfplat libreairie or something? any ideas?

**Comment by gardotd426** [comment]
That's not how the mfplat works, it has nothing whatsoever to do with specific graphics cards, Windows 7 uses the same mfplat.dll no matter what graphics card is being used. 
What do you see when you try doing the steps you ran above? You're missing a step as well. 
1. Delete the `/pfx/` folder in the `/compatdata` directory for the game.
2. Open the game and exit to get it to create a new `/pfx` directory
3. Run `WINEPREFIX=~/path/to/game/pfx/directory/pfx winetricks mf`
4. Run `WINEPREFIX=~/path/to/game/pfx/directory/pfx ./install-mf-64.sh`
5. Copy the mfplat.dll into the game's directory in `steamapps/common`
Notice how you've left out step 3. I imagine that's your problem.

**Comment by z0z0z** [comment]
I have never ran step 3 or heard of anyone doing that with this workaround.

I myself cannot confirm if that helps or breaks things.

**Comment by gardotd426** [comment]
I've always seen it listed as necessary, I've always used it without issue,
actually I've forgotten it before and the game wouldn't work, and then
after running winetricks mf it worked. Maybe that's a coincidence, but
either way....

**Comment by boistordu** [comment]
you know why I thought it was related? because you said this: 

> I've tried the mfplat that fixed the sewer scene as well as the one from this repo
> I acquired an mfplat.dll from another source and it actually started working.

and z0z0 asked: 

> What GPU and driver 

Since I don't know which method exactly are in this dll that's why I was giving these informations.

And apparently it is not the problem since I have the same bug with the white screen parasite. just after the gas station. 
For your information I use the mfplat.dll from this repo. maybe it's not a good one I clearly don't know
but still thanks for the step 3 that I wasn't aware of.

**Comment by gardotd426** [comment]
The mfplat I use now and functions as intended for both RE2 and RE7 is the
one from this repo, so that's not it.

**Comment by gardotd426** [comment]
Closing this issue so people don't think this is still a problem. It's probably something else, as there's an issue open on Proton and mesa's git pages for this game, the mfplat.dll is only for the cutscenes and stuff like that, if the game is otherwise crashing it's probably not because of this.

**Comment by boistordu** [comment]
well the game RE7 or RE2 is only crashing for my part at the cutscenes so it's directly linked to that. Maybe not to the mfplat.dll but again I don't know what's in this file and so I don't know how it interacts with the rest of it.

**Comment by gardotd426** [comment]
Do ANY of the cutscenes work? Or do both games crash at the first cutscene?
if so then yeah, you've done something wrong. Did you try the steps I said
to try?

**Comment by boistordu** [comment]
okey found it.

you need to install mpg123, wine and wine-core which will install a lot more wine packages.
And also you need to start fresh. So redo all the steps after having installed those packages but also start a new game. It would continue to crash after gas station in RE2 if I wouldn't start fresh.

**Comment by gardotd426** [comment]
@boistordu I mean I'm not having that issue, but maybe you're saying "you" for anyone else on Fedora having the issue. There is no `wine-core` package on Arch or Arch-based distributions, nor Ubuntu/Ubuntu-based distributions, and you just need wine or wine-staging. But I do think mpg123 should be added as a dependency to the README if it's not there already, I already have it installed as a dependency for mpd so that might be why I never saw your issue. And just fyi the issues you and I were having were completely different, my cutscenes worked except for a very specific one near the end of the game of RE2. 

@z0z0z would you be open to adding `mpg123` to the dependency list along with python, cabextract and wine? If it's truly a dependency, that is.

**Comment by gardotd426** [comment]
(I know it's not a dependency for the script to run or anything, but it seems like it's a dependency for it to function)
