### ISSUE TITLE
wineprefix

### ISSUE THREAD

**Issue by boistordu** [z0z0z/mf-installcab#15]
Sorry but where should point the prefix? To the local files of the game in question or the specific `compatdata/883710 `because if it's the latter then it doesn't exist.

**Comment by z0z0z** [comment]
A wine prefix could be anywhere on your filesystem. You can make them literally anywhere.

`compatdata/883710`

883710 is the Steam ID of Resident Evil 2. The file path in the README is just used as an example.

You need to find and choose what WINEPREFIX you want. WINEPREFIX folders will have a `drive_c` folder and `system.reg` file inside them at their root.

**Comment by boistordu** [comment]
would you know which ID would it be for resident evil 7 or how to identify the id of one of the game in steam?

**Comment by boistordu** [comment]
okey I manage to find the id 418370 based on this: https://steamdb.info/search/?a=app&q=resident+evil don't know if there is a command line or anything for this.
There is clearly aan improvement with your script but the game needs to be launch in 4.11 proton not 5.0 because it gives an error otherwise. 
And also at every cutscene it will crash. So I didn't get very far. Did I forgot a requirement or something?

**Comment by z0z0z** [comment]
The script has no control over what Proton version you use for a game.

I've heard Resident Evil 7 still often crashes even with this workaround, particularly the opening cutscene that you just simply have to get lucky to play.

**Comment by boistordu** [comment]
okey so the mlffundation that you script is installing has nothing to do with any media files that would are played by the game, correct?

**Comment by z0z0z** [comment]
wut

**Comment by boistordu** [comment]
I need to understand what mf is all about and why it was not installed directly by steam if it is so essential to run those games. And if it is linked to anything related to the media codecs or anything would be explaining why there was an infinity loop before playing the opening cutscene or why it is crashing at each cutscene apparently. So why this mf files are so important? After all you've build a whole script for that thing to be installed so you might know better than me...

**Comment by z0z0z** [comment]
Media Foundation is used by some modern Windows games to play video and audio.

Wine currently doesn't have support for it (although it's being worked on).

This workaround provides Media Foundation DLL libraries from Windows, which can make some games play video/audio. It's not included in Wine or Proton because they legally can't, and even if they could it is nothing but a dirty hack that sometimes work and sometimes doesn't, not proper Media Foundation support.

**Comment by boistordu** [comment]
okey so yeah it's directly link to the playability of the media files. 
so at the end of your script you are talking of mfplat.dll but you doesn't specify in which folder to put it. you say the application folder but it could mean the commonpat folder in the system32 of the cdrive for example or at the root of the RE folder in steamapps ? Because there is a 1kb mfplat in system32 too.

and also you are talking about three dependencies but it is not specified if we are needed to manually install them or not? or steam for example or even lutris or doing that for you ? especially for cabextract

**Comment by z0z0z** [comment]
The application directory is the directory with the `.exe` file

Regarding your question about dependencies, you typically install software through your package manager on Linux. You could of course manually compile them too.

**Comment by boistordu** [comment]
okey because there is also a mfplat.dll in the `compatdata/883710/drive_c/windows/system32/ `which is 1kb

**Comment by z0z0z** [comment]
Those are stubbed/placeholder dll libraries from Wine.

**Comment by boistordu** [comment]
resolutiuon there: [there](https://github.com/z0z0z/mf-installcab/issues/12#issuecomment-592493119)
