### ISSUE TITLE
I cant reinstall this after having cancelled a previous download

### ISSUE THREAD

**Issue by edoantonioco** [z0z0z/mf-installcab#2]
so I tried to install this with the command

]$ sudo WINEPREFIX="/media/DocumentosEXT4/SteamLibrary/steamapps/compatdata/462780/pfx/" ./install-mf-64.sh

and it worked, but I cancedded the download.

Now I rebooted the pc, tried again, and now I cant. It says:

`pc mf-installcab-master]$ sudo WINEPREFIX="/media/DocumentosEXT4/SteamLibrary/steamapps/compatdata/462780/pfx/" ./install-mf-64.sh
mediafoundation
windows6.1-KB976932-X64.exe: no valid cabinets found
Traceback (most recent call last):
  File "installcab.py", line 304, in <module>
    output_files = extract_from_installer(cabfile, tmpdir, component)
  File "installcab.py", line 193, in extract_from_installer
    subprocess.check_output(cmd)
  File "/usr/lib/python2.7/subprocess.py", line 223, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['cabextract', '-F', '*mediafoundation*', '-d', '/tmp/tmppJwCcA', 'windows6.1-KB976932-X64.exe']' returned non-zero exit status 1
`

**Comment by z0z0z** [comment]
1) Don't run this with sudo

2) The script downloads `windows6.1-KB976932-X64.exe` from Microsoft's servers, since you cancelled half way through it's corrupt, delete that file and run the script again.
