### ISSUE TITLE
Resident Evil 3 crashes at the S.T.A.R.S. office.

### ISSUE THREAD

**Issue by laichiaheng** [z0z0z/mf-installcab#21]
If I enter the office, the game crashes.
https://github.com/ValveSoftware/Proton/files/4428284/steam-952060.log

**Comment by Ayushmaniar** [comment]
> If I enter the office, the game crashes.
> https://github.com/ValveSoftware/Proton/files/4428284/steam-952060.log

Hey there, the same is happening with me, as soon as carlos detonates the electronic detonator with the battery, the games crashes and the error we get is 

Unhandled exception: page fault on read access to "blabla" in 64-bit code "blablabla"

Please let me know if you were able to solve this issue, I badly want to finish this game to the end. 

@z0z0z , it would be really helpful if you can have a look at this error and thanks a lot for all your help. I wouldnt have been able to play RE7 or RE2 without you.

Thanks a ton in advance

**Comment by z0z0z** [comment]
This is not recommended to be used at all with RE3, it will crash at the STARS office and other places in the game no matter what.

Using Proton-GE works for fully playing through RE3

https://github.com/GloriousEggroll/proton-ge-custom/releases

Just put it in `~/.steam/steam/compatibilitytools.d`
