### ISSUE TITLE
Update the Documentation

### ISSUE THREAD

**Issue by famouswolfe** [z0z0z/mf-installcab#6]
The documentation could use a little clarification regarding installation of this installer script. Specifically, you should mention that users need to launch the game first as that's what actually creates the "/home/user-name/.steam/steam/steamapps/compatdata/883710/pfx" directory. I spent a good 15 minutes almost ripping my hair out before I figured this out lol. I made the mistake of downloading RE2 from Steam and then trying to install this script before actually launching the game. Just a heads up, keep up the good work!

**Comment by z0z0z** [comment]
Thanks for the feedback, but I don't think I should tell people that the Wine prefix actually needs to be a Wine prefix.

Also this is not just for Proton/Steam. You can create a Wine prefix without any game and install this to it.
